export const TOPIC_STATUSES = {
  draft: 'draft',
  ideation: 'ideation',
  inProgress: 'inProgress',
  voting: 'voting',
  followUp: 'followUp',
  closed: 'closed',
} as const;

export const TOPIC_CATEGORIES = {
  agriculture: 'agriculture',
  animal_protection: 'animal_protection',
  arts: 'arts',
  business: 'business',
  civil_society: 'civil_society',
  communities: 'communities',
  culture: 'culture',
  defence: 'defence',
  democracy: 'democracy',
  diversity: 'diversity',
  education: 'education',
  entertainment: 'entertainment',
  environment: 'environment',
  equality: 'equality',
  health: 'health',
  human_rights: 'human_rights',
  legal: 'legal',
  media: 'media',
  migration: 'migration',
  politics: 'politics',
  public_transportation: 'public_transportation',
  religion: 'religion',
  science: 'science',
  social_welfare: 'social_welfare',
  sports: 'sports',
  taxes: 'taxes',
  technology: 'technology',
  urban_development: 'urban_development',
  work: 'work',
  youth: 'youth',
} as const;

export const TOPIC_VISIBILITY = {
  public: 'public',
  private: 'private',
} as const;
